/* A decorative 0–100% love meter, then a personal birthday welcome. */
(()=>{'use strict';
const root=document.documentElement,overlay=document.getElementById('loveIntro'),site=document.getElementById('birthdaySite');
const $=id=>document.getElementById(id),reduce=matchMedia('(prefers-reduced-motion: reduce)');
const scenes=[
 {overline:'GỬI NGƯỜI ANH THƯƠNG NHẤT',title:'Chào Vợ yêu<br><em>Minh Hân của anh.</em>',text:'Là anh đây, Chó Béo của em. Trước khi mở món quà này, cho anh được nói với em vài điều nhé.',aside:'Em cứ chậm rãi thôi. Hôm nay, mọi dịu dàng đều dành cho em.',duration:6500},
 {overline:'TỪ HÀN QUỐC, ANH GỬI EM MỘT CÁI ÔM',title:'Xa em một khoảng trời,<br><em>thương em thì thật gần.</em>',text:'Anh đang ở Hàn Quốc học thạc sĩ, nên sinh nhật này không thể ở bên em, ôm em và cùng em thổi nến. Anh ước mình có thể bước qua màn hình, để được nói lời chúc ngay bên cạnh em.',aside:'Hôm nay anh nhớ em. Nhiều hơn một chút nữa.',duration:11000},
 {overline:'MỘT MÓN QUÀ NHỎ, THAY ANH Ở BÊN EM',title:'Vậy nên, anh gửi<br><em>yêu thương vào đây.</em>',text:'Vào những bức ảnh của chúng mình, vào từng dòng chữ và những trái tim bé xíu. Mong khi mở món quà này, em sẽ mỉm cười và cảm thấy anh đang ở gần bên.',aside:'Khoảng cách chỉ làm cái ôm đến muộn, không làm anh thương em ít đi.',duration:9500},
 {overline:'29.09.2026 · NGÀY CỦA RIÊNG EM',title:'Sinh nhật vui vẻ,<br><em>Vợ Cún yêu của anh.</em>',text:'Ước gì hôm nay anh có thể nắm tay em. Còn lúc này, em đưa tay đây — mình cùng mở món quà nhỏ anh dành riêng cho em nhé.',aside:'Thương em thật nhiều. — Chó Béo ♡',duration:0}
];
let active=false,stage=-1,paused=false,timer=0,frame=0,progressStart=0,pct=-1,finished=false,changing=false,sceneDue=0,remaining=0,hiddenAt=0,generation=0;
const later=(fn,ms)=>{clearTimeout(timer);timer=setTimeout(fn,ms)};
function unlock(){root.classList.remove('intro-pending');site.inert=false;site.removeAttribute('aria-hidden');}
function finish(){if(!active||finished)return;finished=true;active=false;generation++;clearTimeout(timer);cancelAnimationFrame(frame);unlock();overlay.classList.add('leaving');site.classList.add('intro-entering');window.scrollTo({top:0,behavior:'instant'});const heading=site.querySelector('h1');heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});const exitGeneration=generation;setTimeout(()=>{if(generation!==exitGeneration)return;overlay.hidden=true;overlay.classList.remove('leaving');site.classList.remove('intro-entering')},reduce.matches?0:1200);}
function arm(ms){remaining=ms;sceneDue=performance.now()+ms;if(ms&&!paused&&!document.hidden)later(next,ms);}
function renderScene(n){if(!active)return;stage=n;changing=false;$('introLoading').hidden=true;$('introStory').hidden=false;const s=scenes[n],copy=$('storyCopy');copy.classList.remove('story-changing','story-reveal');copy.style.animation='none';void copy.offsetWidth;copy.style.animation='';copy.classList.add('story-reveal');$('storyOverline').textContent=s.overline;$('storyTitle').innerHTML=s.title;$('storyText').textContent=s.text;$('storyAside').textContent=s.aside;document.querySelectorAll('.story-dots span').forEach((el,i)=>{el.classList.toggle('active',i===n);el.setAttribute('aria-label',`Lời nhắn ${i+1}${i===n?', hiện tại':''}`)});$('nextIntro').innerHTML=n===3?'Mở món quà của anh <span aria-hidden="true">♡</span>':'Nghe anh nói tiếp <span aria-hidden="true">→</span>';$('nextIntro').classList.toggle('final-gift',n===3);$('pauseIntro').hidden=n===3;arm(s.duration);}
function next(){if(!active||changing)return;if(stage===3){finish();return}clearTimeout(timer);changing=true;$('storyCopy').classList.add('story-changing');later(()=>renderScene(stage+1),reduce.matches?0:350);}
function progress(t){if(!active||stage!==-1)return;if(document.hidden){frame=0;return}if(!progressStart)progressStart=t;const duration=reduce.matches?1600:4800,p=Math.min(1,(t-progressStart)/duration);const value=Math.min(100,Math.floor(100*(p*p*(3-2*p))));if(value!==pct){pct=value;$('heartPercent').innerHTML=value+'<span>%</span>';document.querySelector('.heart-loader').setAttribute('aria-valuenow',String(value));$('heartLiquid').setAttribute('transform',`translate(0 ${185-value*1.72})`);$('introMeter').style.width=value+'%';$('loadingNote').textContent=value<32?'Anh đang gom những điều dịu dàng nhất…':value<68?'Thêm một chút nhớ, một chút thương em…':value<100?'Gói lại bằng một cái ôm thật lâu…':'Đủ 100% yêu thương. Gửi đến em, ngay đây ♡';}if(p<1){frame=requestAnimationFrame(progress)}else{document.querySelector('.heart-loader').classList.add('complete');later(()=>renderScene(0),reduce.matches?250:800)}}
function start(){generation++;clearTimeout(timer);cancelAnimationFrame(frame);active=true;finished=false;changing=false;stage=-1;paused=reduce.matches;progressStart=0;pct=-1;hiddenAt=0;overlay.hidden=false;overlay.classList.remove('leaving');site.classList.remove('intro-entering');root.classList.add('intro-pending');site.inert=true;site.setAttribute('aria-hidden','true');$('introLoading').hidden=false;$('introStory').hidden=true;$('heartPercent').innerHTML='0<span>%</span>';$('introMeter').style.width='0%';$('heartLiquid').setAttribute('transform','translate(0 185)');document.querySelector('.heart-loader').classList.remove('complete');$('pauseIntro').textContent=paused?'Tự động chuyển lời nhắn':'Tạm dừng lời nhắn';$('pauseIntro').setAttribute('aria-pressed',String(paused));$('skipIntro').focus({preventScroll:true});frame=requestAnimationFrame(progress);}
try{
const petals=document.querySelector('.intro-petals');for(let i=0;i<14;i++){const h=document.createElement('span');h.textContent=i%3?'♡':'♥';h.style.cssText=`--x:${(i*37)%100}%;--size:${11+i%4*5}px;--duration:${12+i%6*2}s;--delay:${-i*1.7}s`;petals.appendChild(h)}
$('skipIntro').onclick=finish;$('nextIntro').onclick=next;$('replayIntro').hidden=false;$('replayIntro').onclick=start;
$('pauseIntro').onclick=()=>{if(changing)return;paused=!paused;if(paused){remaining=Math.max(0,sceneDue-performance.now());clearTimeout(timer)}else if(stage>=0&&!changing){arm(remaining||scenes[stage].duration)}$('pauseIntro').textContent=paused?'Tiếp tục lời nhắn':'Tạm dừng lời nhắn';$('pauseIntro').setAttribute('aria-pressed',String(paused));};
overlay.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finish()}if(e.key==='Tab'){const items=[...overlay.querySelectorAll('button')].filter(el=>el.getClientRects().length),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
document.addEventListener('visibilitychange',()=>{if(!active)return;if(document.hidden){hiddenAt=performance.now();cancelAnimationFrame(frame);if(stage>=0){remaining=Math.max(0,sceneDue-performance.now());clearTimeout(timer);if(changing)renderScene(stage+1)}}else{if(stage===-1){if(progressStart)progressStart+=performance.now()-hiddenAt;frame=requestAnimationFrame(progress)}else if(!paused&&!changing&&stage<3)arm(remaining||scenes[stage].duration);hiddenAt=0}});
start();
}catch(error){clearTimeout(timer);cancelAnimationFrame(frame);active=false;overlay.hidden=true;unlock();console.error('Intro unavailable:',error)}
})();
